# Generated by Django 2.2.1 on 2019-08-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190826_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dns', models.TextField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Country')),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Date')),
                ('ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Ip')),
            ],
        ),
    ]
